### ISSUE TITLE
Can't build in xcode

### ISSUE THREAD

**Issue by clang1974** [super-ultra/ScrollMechanics#1]
Gets the error: Framework not found Pods_ScrollMechanics

Perhaps I'm doing something wrong?

I have adopted much of the ScrollMechanics source code into a few applications of mine through cut and paste.  I have made some updates which expand on it, so I wanted to submit them as a return gesture for creating this useful repo.  But I'm not able to clone and get it to build in Xcode due to the above error.

**Comment by super-ultra** [comment]
You are right! 
It was necessary to install Pods. But it was empty. So I deleted Podfile and staff and fixed the error.
Thank you.
#2
