### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by wearhere** [super-ultra/ScrollMechanics#3]
Thank you so much for this amazing repo and your explanation behind it at https://medium.com/@esskeetit/%D0%BA%D0%B0%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-uiscrollview-2e7052032d97. I'm not sure that I've ever seen more thorough, yet easy-to-understand, reverse-engineering.

I'd love to use this in an application of my own and am curious if you could add a license to permit doing so? Some options can be found at https://choosealicense.com/. I typically use the [MIT license](https://choosealicense.com/licenses/mit/) for my own work, for what it's worth.

**Comment by super-ultra** [comment]
Done. Thank you!
